[Icon Theme]
Name=Sevi
Comment=Mix of Lüv and Reversal icons with some additions.
Inherits=Papirus,Adwaita,hicolor
Example=folder

# KDE/Plasma Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,96,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
FollowsColorScheme=true

KDE-Extensions=.svg

# Directory list
Directories=apps/scalable,apps/symbolic,places/16,places/22,places/24,places/48,places/symbolic,status/16,status/22,status/24,status/32,status/symbolic,apps@2x/scalable,apps@2x/symbolic,places@2x/symbolic,places@2x/48,places@2x/16,places@2x/22,places@2x/24,status@2x/16,status@2x/22,status@2x/24,status@2x/32,status@2x/symbolic

[apps/scalable]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/symbolic]
Size=16
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
MinSize=22
MaxSize=512
Type=Scalable

[places/symbolic]
Size=16
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

# @2x

[apps@2x/scalable]
Size=64
Scale=2
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps@2x/symbolic]
Size=16
Scale=2
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[places@2x/16]
Size=16
Scale=2
Context=Places
Type=Fixed

[places@2x/22]
Size=22
Scale=2
Context=Places
Type=Fixed

[places@2x/24]
Size=24
Scale=2
Context=Places
Type=Fixed

[places@2x/48]
Size=48
Scale=2
Context=Places
MinSize=22
MaxSize=512
Type=Scalable

[places@2x/symbolic]
Size=16
Scale=2
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[status@2x/16]
Size=16
Scale=2
Context=Status
Type=Fixed

[status@2x/22]
Size=22
Scale=2
Context=Status
Type=Fixed

[status@2x/24]
Size=24
Scale=2
Context=Status
Type=Fixed

[status@2x/32]
Size=32
Scale=2
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status@2x/symbolic]
Size=16
Scale=2
Context=Status
MinSize=16
MaxSize=512
Type=Scalable
